version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
linters:
  default: "all"
  disable:
    - cyclop
    - gocognit
    - gomodguard
    - inamedparam
    - lll
    - makezero
    - nestif
    - mnd
    - musttag
    - nlreturn
    - perfsprint
    - testpackage
    - varnamelen
    - wsl
  exclusions:
    presets:
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - funlen
  settings:
    depguard:
      rules:
        lib:
          files: 
            - "**/lib/*.go"
          list-mode: strict
          allow:
            - $gostd
            - "golang.org/x/crypto/argon2"
            - "golang.org/x/crypto/chacha20poly1305"
    godox:
      keywords:
        - fixme
    gomoddirectives:
      replace-local: true
    revive:
      enable-all-rules: false
      rules:
        - name: exported
          disabled: true
    wrapcheck:
      extra-ignore-sigs:
        - .WrapErrorf
