name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'
    
    - name: Build tools
      run: ./build.sh tools
    
    - name: Format check
      run: ./build.sh fmt
    
    - name: Lint
      run: ./build.sh lint
    
    - name: Build
      run: ./build.sh build
    
    - name: Test
      run: ./build.sh test
    
    - name: Bash integration tests
      run: ./build.sh test integration-bash
